### ISSUE TITLE
Problème de bibliographie

### ISSUE THREAD

**Issue by GuyliannEngels** [charlottemisson/charlotte-misson-blog#1]
Salut @charlottemisson ,

Suite à nos échanges de mails, tu viens de m'ajouter comme collaborateur du projet. 
Voici ta demande

Bonjour Monsieur, 
Je voudrais mettre à jour mon blog, mais je bloque au niveau de la bibliographie. 
Voici l'erreur que la console me donne.
Pourriez-vous m'indiquer la marche à suivre?
Merci, 
Cordialement, 
Charlotte Misson

Je vais regarder à ton problème

**Comment by GuyliannEngels** [comment]
Le problème peut venir de plusieurs endroits tout d'abord, il y a plusieurs fichiers mal rangés 

## dans le dossier _posts

Tu as un dossier avec _2019-10-16-nom-de-votre-article_ qui semble correspondre à ton premier article dont le titre est **It's time** . Ensuite tu as deux fichiers article1.Rmd et sa version compilée HTML. 
Les fichiers article1 ne devraient ils pas être supprimé ? 

## Le dossier Bibliographie 

Le dossier bibliographie comprend un dossier se terminant par l'extension .bib. Tu dois refaire ton fichier car tu parle d'article alors que je ne pense pas que tu as employée des articles scientifiques

**Comment by GuyliannEngels** [comment]
J'ai néanmoins ajouté un nouveau fichier de biblio qui s'exécute maintenant. N'oublie pas de faire un PULL

Si tu n'as plus de questions, penses à fermer cette issue

**Comment by charlottemisson** [comment]
Merci pour votre aide, Bonne journée, 
Charlotte.
