### ISSUE TITLE
problème avec github

### ISSUE THREAD

**Issue by charlottemisson** [charlottemisson/charlotte-misson-blog#2]
Bonjour monsieur,
désolée de vous déranger encore. 
J'ai fais le commit de mon article, mais lorsque je veux faire un "push", il me met un message d'erreur 
![Screenshot_2019-10-18_12-50-00](https://user-images.githubusercontent.com/55578658/67088966-ca281380-f1a6-11e9-9267-4c0366ce7fa0.png)

Du coup, je ne vois pas la dernière version de mon article sur mon blog. 
Pourriez-vous m'aider? 
D'avance merci, 
Charlotte.

**Comment by GuyliannEngels** [comment]
Salut @charlottemisson ,

L'erreur est évidente. Lis le message d'erreur. Tu n'as pas fais ton PULL avant de travailler 

Bonne journée

**Comment by GuyliannEngels** [comment]
PS : N'oublie pas de me tagger dans tes nouvelles issues, sinon je pourrais rater ton mail

**Comment by charlottemisson** [comment]
![Screenshot_2019-10-18_16-55-15](https://user-images.githubusercontent.com/55578658/67104971-3b2bf300-f1c8-11e9-91c9-91dc48913b4b.png)
Lorsque je veux faire le pull, nouveau message d'erreur...

**Comment by GuyliannEngels** [comment]
Essaye de bien enregistré tous tes fichiers, fais un commit, puis un PULL 
dis moi ensuite si le problème persiste

**Comment by charlottemisson** [comment]
J'ai réussi à faire le commit et le pull. 
Par contre, c'est toujours l'ancienne version de mon article sur le blog.

**Comment by GuyliannEngels** [comment]
Maintenant que tu as ton pull, il te reste à faire ton push pr envoyer tes modifs

**Comment by charlottemisson** [comment]
ça fonctionne! merci pour votre aide, bon week-end. 
Je ferme l'issue.
