### ISSUE TITLE
modification de la section 

### ISSUE THREAD

**Issue by GuyliannEngels** [charlottemisson/charlotte-misson-blog#3]
Salut @charlottemisson ,

Je reprends tes mails pour débuter notre discussion 

- Ta demande
> Bonjour Monsieur, 
J'ai commencé à faire les modifications demandées. 
Elles apparaissent lorsque je fais un "knit" dans R, mais n'apparaissent pas dans le blog sur un moteur de recherche alors que j'ai fais un commit, push et build website. 
Comment dois-je faire? 
D'avance merci

- Ma réponse 

> Je vois pour ma part tes modifications. 
Tu dois prendre l’url de ton blog et l’ouvrir dans une fenêtre de navigation privé de ton moteur de recherche.

- Ta demande 

>La modification de l'onglet "English" en post est effective en effet, mais j'ai modifié la couleur et ajouté un logo et ça je ne le vois pas. 
Merci pour votre aide, 
bonne soirée

- Ma réponse

> J ouvre une issue afin de discuter en contexte

**Comment by GuyliannEngels** [comment]
Maintenant que nous sommes dans une issue et de ce fait dans le contexte de ta problématique  @charlottemisson. Nous sommes plus à mêne de discuter efficacement.

à première vue, tu renseignes convenablement ton fichier css dans le fichier _site.yml

![Capture d’écran 2019-11-06 à 08 32 17](https://user-images.githubusercontent.com/33956170/68277705-09dc6f80-0070-11ea-8a5e-5fb5f71eaa8a.png)

Ton fichier css ne semble pas contenir des erreurs, peut être que la présence des espaces entre chaque ligne pose problème. Je ne suis pas sur de mon coup. Peux tu me nommer comme collaborateur de ton projet comme cela je pourrais plus facilement analyser ton site en local et pas simplement en lisant les fichiers sur GitHub

**Comment by charlottemisson** [comment]
Bonjour Monsieur, 
Merci pour votre réponse. 
J'ai enlevé tous les espaces dans le fichier .css et cela fonctionne!
Merci pour votre aide,
belle journée
Charlotte.
